.TH "system-config-users" "8" "7 February 2004" "System Config Tools Manual" "System Config Tools Manual"

.SH NAME
system\-config\-users \- User and Group Management tool

.SH SYNOPSIS
.B system-config-users

.SH DESCRIPTION
\fBsystem-config-users\fP provides a graphical interface for adding and
removing users and groups to the system.  Once started
\fBsystem-config-users\fP provides a help feature to assist in learning the
interface.

.SH OPTIONS
None

.SH FILES
\fi/usr/bin/system-config-users\fP
.br
\fi/usr/share/doc/system-config-users*\fP

.SH Examples
To run the program type:

system-config-users

.SH REPORTING BUGS
Report bugs to <http://bugzilla.redhat.com>.

.SH LICENSE AND AUTHORS
\fBsystem-config-users\fP is licensed under the GNU Public License and
is copyrighted by Red Hat, Inc.
.br
Online Documentation by Tammy Fox <tfox@redhat.com>
.br
Manpage by Chris Spencer <chris@spencer-family.org>
